### ISSUE TITLE
Exception: Failed to load XML file

### ISSUE THREAD

**Issue by erwincoumans** [google-research/robel#5]
After following the README and installing robel, running the example script, I got this error:
~~~~~~~~~~~~~~~~~~~
erwincoumans-macbookpro2:robel erwincoumans$ source ~/.bash_profile
erwincoumans-macbookpro2:robel erwincoumans$ python3 -m robel.scripts.rollout -e DClawTurnFixed-v0 --render
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/erwincoumans/develop/robel/robel/scripts/rollout.py", line 254, in <module>
    rollout_script()
  File "/Users/erwincoumans/develop/robel/robel/scripts/rollout.py", line 198, in rollout_script
    env = gym.make(env_id)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/Users/erwincoumans/develop/robel/robel/utils/configurable.py", line 102, in __init__
    base_init(self, *args, **kwargs)
  File "/Users/erwincoumans/develop/robel/robel/dclaw/turn.py", line 71, in __init__
    **kwargs)
  File "/Users/erwincoumans/develop/robel/robel/dclaw/base_env.py", line 174, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/erwincoumans/develop/robel/robel/dclaw/base_env.py", line 75, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/erwincoumans/develop/robel/robel/robot_env.py", line 103, in __init__
    sim_model, backend=sim_backend, frame_skip=frame_skip)
  File "/Users/erwincoumans/develop/robel/robel/simulation/sim_scene.py", line 49, in create
    return mjpy_sim_scene.MjPySimScene(*args, **kwargs)
  File "/Users/erwincoumans/develop/robel/robel/simulation/sim_scene.py", line 72, in __init__
    self.sim = self._load_simulation(model_handle)
  File "/Users/erwincoumans/develop/robel/robel/simulation/mjpy_sim_scene.py", line 58, in _load_simulation
    model = mujoco_py.load_model_from_path(model_handle)
  File "mujoco_py/cymj.pyx", line 175, in mujoco_py.cymj.load_model_from_path
Exception: Failed to load XML file: /Users/erwincoumans/develop/robel/robel/dclaw/assets/dclaw3xh_valve3_v0.xml. mj_loadXML error: b"XML Error: Include error: 'XML parse error at line 0, column 0:\nFailed to open file\n'\nElement 'include', line 19, column 3\n"
~~~~~~~~~~~~~~~~~~~

**Comment by vikashplus** [comment]
Note that ROBEL uses git-submodules for dependencies. It seems like the error is due to the missing submodule. Detailed instructions for installing with submodules are provided in the read me page. More concretely please use -
`git clone --recurse-submodules https://github.com/google-research/robel.git`

**Comment by 1434916964** [comment]
did it solved? i met the same problem

**Comment by vikashplus** [comment]
@1434916964 - Please note my suggestion above. It worked for me last time.
